project:
  title: "CounterfactualExplanations.jl"
  execute-dir: project
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
bibliography: https://raw.githubusercontent.com/pat-alt/bib/main/bib.bib
jupyter: julia-1.8


