[cats_dogs_data]
git-tree-sha1 = "353f18d6492ab31cddb0e874e71e38535d49c68e"
lazy = true

    [[cats_dogs_data.download]]
    sha256 = "aca3df23d230a913ad3c2a7e12bd4c10ff7e69230bdee2ecf496b04d9fe25a3f"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_data.tar.gz"

[cats_dogs_images]
git-tree-sha1 = "4f62372007fc7f73c108720000861bc412a4b759"
lazy = true

    [[cats_dogs_images.download]]
    sha256 = "2c0a849fbc4e7258399a8b822281d241c1027d9521026d3ef26d9faa7385b05d"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_images.tar.gz"

[cats_dogs_laplace]
git-tree-sha1 = "79fd6ec6bb5800e775a9680fbbe7d0df046411ea"
lazy = true

    [[cats_dogs_laplace.download]]
    sha256 = "15b0cd4819c63218589a87ad04a2e711d7747bb356b9e6fef2d55eca87a97d55"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_laplace.tar.gz"

[cats_dogs_model]
git-tree-sha1 = "71fdacce1cd28aa26b3e8dd1c4d3c582dbd674f2"
lazy = true

    [[cats_dogs_model.download]]
    sha256 = "6f43a710595ecc6f287ba8230a5185202fd3a73a8fd30620db560ca4ef89f335"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_model.tar.gz"

[mnist_data]
git-tree-sha1 = "57053f5d58979856be84cac48992177fc01f6f73"
lazy = true

    [[mnist_data.download]]
    sha256 = "d4015651dbf225b665afb8127754288154a908a713b7729ce4b85f9719fe4feb"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_data.tar.gz"

[mnist_ensemble]
git-tree-sha1 = "0e3da48162ef41f773188cddff6e33cea907acf3"
lazy = true

    [[mnist_ensemble.download]]
    sha256 = "16b7b5b9b8c041f77a3467f160a4b7d0846401c3c4450d369f7b629121907141"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_ensemble.tar.gz"

[mnist_model]
git-tree-sha1 = "f50f427bbbee546d402de6053912ba3d4fd227bc"
lazy = true

    [[mnist_model.download]]
    sha256 = "6a696e6477ddd1a4a1d60e792becfd657014358bfbb72048be28d1d05880d8e0"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_model.tar.gz"

[models_flux]
git-tree-sha1 = "6d78dc08a773cd6b54536413f2acc9a66419042d"
lazy = true

    [[models_flux.download]]
    sha256 = "cbf11e30709c04ce417652e88e5bb007d4b4907465d7db6a1777efe0e8402337"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/models_flux.tar.gz"

[models_models]
git-tree-sha1 = "a47e8a6ba2cbc0950b7be184d2c7b0c550c80f50"
lazy = true

    [[models_models.download]]
    sha256 = "9440819cdf0bafae648e73fc32f0cb5bdd799bce67ab8174a6d6f106ae1a605d"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/models_models.tar.gz"

[models_r]
git-tree-sha1 = "d58ff24bd87b1291a8421142f3ac17259b6a1887"
lazy = true

    [[models_r.download]]
    sha256 = "4f59d90a11a2a26d38c0dd08297710768623cf8696c2c93b8875fd3828207400"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/models_r.tar.gz"

[models_r_torch]
git-tree-sha1 = "ce37867b98fcee44a78aeda3a96157de8a8646be"
lazy = true

    [[models_r_torch.download]]
    sha256 = "204041a1e9aaf7a5f13def21703acb1db8275b796fe513b1c9f0af4194032b53"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/models_r_torch.tar.gz"

[synthetic_data]
git-tree-sha1 = "7b9bfa45ce592f574f825986b7408258c9d773ea"
lazy = true

    [[synthetic_data.download]]
    sha256 = "af01647d9c16b7df76de727691cf2b508fb2cec363d9305fa09036de7768d1c2"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_data.tar.gz"

[synthetic_flux]
git-tree-sha1 = "f506561e34a38cc4e778c32640e10882c8849639"
lazy = true

    [[synthetic_flux.download]]
    sha256 = "08517aa5e213773146a6dfce7ad3995e19d49a0e9953fff123228e0b4f775a32"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_flux.tar.gz"

[synthetic_r_torch]
git-tree-sha1 = "a2a49a7c7d9133c21b429c5ed133deeb29339436"
lazy = true

    [[synthetic_r_torch.download]]
    sha256 = "1776a77209237087d6fa4b0d68e1c22d29b507da2fe8515086b829f4c03d00e2"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_r_torch.tar.gz"

[ucr_data]
git-tree-sha1 = "6767d796c1f5e75d924f1cd72c0bec2dbaf46dfe"
lazy = true

    [[ucr_data.download]]
    sha256 = "e474c53de1cb8ed974e0a4ccfd13b93a58bd5fe445eee348a0889bc4cc4a0d48"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_data.tar.gz"

[ucr_model]
git-tree-sha1 = "0f66aebcbafc26fbc2e151a02ec527864dbe1206"
lazy = true

    [[ucr_model.download]]
    sha256 = "6b9d8aae8b2e1065494910f0c519d4c60bada9e08b6e0f45e794c36588c20522"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_model.tar.gz"
