[cats_dogs_data]
git-tree-sha1 = "9a272c52b173982900a7c74933590b66df80145c"
lazy = true

    [[cats_dogs_data.download]]
    sha256 = "79ffbbec894abaf909430854dffdee1a8cbd665eeee120fe536d2a4ab825585a"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_data.tar.gz"

[cats_dogs_images]
git-tree-sha1 = "c13137bef293f3bb5c50158574fafd3b2147650a"
lazy = true

    [[cats_dogs_images.download]]
    sha256 = "09b6927f66980428003616ced26be88658c509f04e0f4692237f7ec69430a9b0"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_images.tar.gz"

[cats_dogs_laplace]
git-tree-sha1 = "15b085972667f6740b99b786fbb12212cc54051a"
lazy = true

    [[cats_dogs_laplace.download]]
    sha256 = "322b47f14d2c19d7cd18fcea3c69bb15efccffd49159dd50dbf292bddd4ccd92"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_laplace.tar.gz"

[cats_dogs_model]
git-tree-sha1 = "133ac812fae6e722f8cb992c780cfbf2af89a03c"
lazy = true

    [[cats_dogs_model.download]]
    sha256 = "80edd9eba1845475887ff93fd779bd29946ede6e2071bb9745bc01d2db79eef6"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_model.tar.gz"

[mnist_data]
git-tree-sha1 = "20ad5a70ff88d00a437c6ac6d9ef1f41cbddae46"
lazy = true

    [[mnist_data.download]]
    sha256 = "6dcc563134a2d49125392b3cb7e923c7ce9a30e1c388bc79b0d15b6274552e05"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_data.tar.gz"

[mnist_ensemble]
git-tree-sha1 = "3242c0c596d2f1da9c97cc2472c492ffd72f3844"
lazy = true

    [[mnist_ensemble.download]]
    sha256 = "0d89ef42dd5bf79fde1e63b556bb27803c1bf5f6af4fe8fce0155a65aae60e98"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_ensemble.tar.gz"

[mnist_model]
git-tree-sha1 = "70ba6f5f2d8c44b42ef6f5fd761f807187cc5e16"
lazy = true

    [[mnist_model.download]]
    sha256 = "894c04879d83c01c76bd7dc2ca4c0aa02b9814abbcdff6ec37b3f44e5920e352"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_model.tar.gz"

[ucr_data]
git-tree-sha1 = "6767d796c1f5e75d924f1cd72c0bec2dbaf46dfe"
lazy = true

    [[ucr_data.download]]
    sha256 = "e474c53de1cb8ed974e0a4ccfd13b93a58bd5fe445eee348a0889bc4cc4a0d48"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_data.tar.gz"

[ucr_model]
git-tree-sha1 = "0f66aebcbafc26fbc2e151a02ec527864dbe1206"
lazy = true

    [[ucr_model.download]]
    sha256 = "6b9d8aae8b2e1065494910f0c519d4c60bada9e08b6e0f45e794c36588c20522"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_model.tar.gz"
