[cats_dogs_data]
git-tree-sha1 = "353f18d6492ab31cddb0e874e71e38535d49c68e"
lazy = true

    [[cats_dogs_data.download]]
    sha256 = "aca3df23d230a913ad3c2a7e12bd4c10ff7e69230bdee2ecf496b04d9fe25a3f"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_data.tar.gz"

[cats_dogs_images]
git-tree-sha1 = "4f62372007fc7f73c108720000861bc412a4b759"
lazy = true

    [[cats_dogs_images.download]]
    sha256 = "2c0a849fbc4e7258399a8b822281d241c1027d9521026d3ef26d9faa7385b05d"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_images.tar.gz"

[cats_dogs_laplace]
git-tree-sha1 = "79fd6ec6bb5800e775a9680fbbe7d0df046411ea"
lazy = true

    [[cats_dogs_laplace.download]]
    sha256 = "15b0cd4819c63218589a87ad04a2e711d7747bb356b9e6fef2d55eca87a97d55"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_laplace.tar.gz"

[cats_dogs_model]
git-tree-sha1 = "71fdacce1cd28aa26b3e8dd1c4d3c582dbd674f2"
lazy = true

    [[cats_dogs_model.download]]
    sha256 = "6f43a710595ecc6f287ba8230a5185202fd3a73a8fd30620db560ca4ef89f335"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_model.tar.gz"

[mnist_data]
git-tree-sha1 = "20ad5a70ff88d00a437c6ac6d9ef1f41cbddae46"
lazy = true

    [[mnist_data.download]]
    sha256 = "6dcc563134a2d49125392b3cb7e923c7ce9a30e1c388bc79b0d15b6274552e05"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_data.tar.gz"

[mnist_ensemble]
git-tree-sha1 = "3242c0c596d2f1da9c97cc2472c492ffd72f3844"
lazy = true

    [[mnist_ensemble.download]]
    sha256 = "0d89ef42dd5bf79fde1e63b556bb27803c1bf5f6af4fe8fce0155a65aae60e98"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_ensemble.tar.gz"

[mnist_model]
git-tree-sha1 = "70ba6f5f2d8c44b42ef6f5fd761f807187cc5e16"
lazy = true

    [[mnist_model.download]]
    sha256 = "894c04879d83c01c76bd7dc2ca4c0aa02b9814abbcdff6ec37b3f44e5920e352"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_model.tar.gz"

[ucr_data]
git-tree-sha1 = "6767d796c1f5e75d924f1cd72c0bec2dbaf46dfe"
lazy = true

    [[ucr_data.download]]
    sha256 = "e474c53de1cb8ed974e0a4ccfd13b93a58bd5fe445eee348a0889bc4cc4a0d48"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_data.tar.gz"

[ucr_model]
git-tree-sha1 = "0f66aebcbafc26fbc2e151a02ec527864dbe1206"
lazy = true

    [[ucr_model.download]]
    sha256 = "6b9d8aae8b2e1065494910f0c519d4c60bada9e08b6e0f45e794c36588c20522"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_model.tar.gz"
