[cats_dogs_data]
git-tree-sha1 = "353f18d6492ab31cddb0e874e71e38535d49c68e"
lazy = true

    [[cats_dogs_data.download]]
    sha256 = "aca3df23d230a913ad3c2a7e12bd4c10ff7e69230bdee2ecf496b04d9fe25a3f"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_data.tar.gz"

[cats_dogs_images]
git-tree-sha1 = "4f62372007fc7f73c108720000861bc412a4b759"
lazy = true

    [[cats_dogs_images.download]]
    sha256 = "2c0a849fbc4e7258399a8b822281d241c1027d9521026d3ef26d9faa7385b05d"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_images.tar.gz"

[cats_dogs_laplace]
git-tree-sha1 = "79fd6ec6bb5800e775a9680fbbe7d0df046411ea"
lazy = true

    [[cats_dogs_laplace.download]]
    sha256 = "15b0cd4819c63218589a87ad04a2e711d7747bb356b9e6fef2d55eca87a97d55"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_laplace.tar.gz"

[cats_dogs_model]
git-tree-sha1 = "71fdacce1cd28aa26b3e8dd1c4d3c582dbd674f2"
lazy = true

    [[cats_dogs_model.download]]
    sha256 = "6f43a710595ecc6f287ba8230a5185202fd3a73a8fd30620db560ca4ef89f335"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/cats_dogs_model.tar.gz"

[mnist_data]
git-tree-sha1 = "57053f5d58979856be84cac48992177fc01f6f73"
lazy = true

    [[mnist_data.download]]
    sha256 = "d4015651dbf225b665afb8127754288154a908a713b7729ce4b85f9719fe4feb"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_data.tar.gz"

[mnist_ensemble]
git-tree-sha1 = "0e3da48162ef41f773188cddff6e33cea907acf3"
lazy = true

    [[mnist_ensemble.download]]
    sha256 = "16b7b5b9b8c041f77a3467f160a4b7d0846401c3c4450d369f7b629121907141"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_ensemble.tar.gz"

[mnist_model]
git-tree-sha1 = "f50f427bbbee546d402de6053912ba3d4fd227bc"
lazy = true

    [[mnist_model.download]]
    sha256 = "6a696e6477ddd1a4a1d60e792becfd657014358bfbb72048be28d1d05880d8e0"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/mnist_model.tar.gz"

[synthetic_data]
git-tree-sha1 = "7b9bfa45ce592f574f825986b7408258c9d773ea"
lazy = true

    [[synthetic_data.download]]
    sha256 = "976992503797a7c76f4c607abd70952dde395d6ca2dc8e8ae3a8ed4b4648e6a2"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_data.tar.gz"

[synthetic_flux]
git-tree-sha1 = "b1d77c45e9e697d18c4c4395a52fc4e27dc5c8dc"
lazy = true

    [[synthetic_flux.download]]
    sha256 = "624d5b7d930c76bd910537f47edeb082f3b2acb13b7bef62eb6ea6d88aac6d78"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_flux.tar.gz"

[synthetic_r_torch]
git-tree-sha1 = "f7f0eb103fc1e3289315484bbad7c30a81677753"
lazy = true

    [[synthetic_r_torch.download]]
    sha256 = "1faf5848a3f6f4d9527b72c6510239493cdaf9a87c31ee60228c95c414b3967e"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/synthetic_r_torch.tar.gz"

[ucr_data]
git-tree-sha1 = "6767d796c1f5e75d924f1cd72c0bec2dbaf46dfe"
lazy = true

    [[ucr_data.download]]
    sha256 = "e474c53de1cb8ed974e0a4ccfd13b93a58bd5fe445eee348a0889bc4cc4a0d48"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_data.tar.gz"

[ucr_model]
git-tree-sha1 = "0f66aebcbafc26fbc2e151a02ec527864dbe1206"
lazy = true

    [[ucr_model.download]]
    sha256 = "6b9d8aae8b2e1065494910f0c519d4c60bada9e08b6e0f45e794c36588c20522"
    url = "https://github.com/pat-alt/CounterfactualExplanations.jl/releases/download/data/ucr_model.tar.gz"
